import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import Navbar from "@/components/common/Navbar";
// import ProgressBarI from "@/components/common/ProgressBar";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Devocode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme={"default"}>
      <body>
        <Providers>
          <Navbar />
          <Toaster position="bottom-center" />

          <main className="mb-24">{children}</main>
          {/* <ProgressBarI /> */}
        </Providers>
      </body>
    </html>
  );
}
